name: Deploy to Staging

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - id: version
        run: echo "::set-output name=version::0.0.1"
    outputs:
      version: ${{ steps.version.outputs.version }}
  test:
    runs-on: ubuntu-latest
    name: test
    needs:
      - build
    steps:
      - name: test
        run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ needs.build.outputs.version }} to Staging
    needs:
     - test
     - build
    environment: staging
    steps:
     - name: deploy
       run: echo "deploy"
  rollback:
    continue-on-error: true
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
     - deploy
    steps:
    - uses: hmarr/debug-action@v2
