name: Deploy to Staging

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - id: version
        run: echo "::set-output name=version::0.0.1"
    outputs:
      version: ${{ steps.version.outputs.version }}
  test:
    runs-on: ubuntu-latest
    name: test
    needs:
      - build
    steps:
      - name: test
        run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - staging
          - beta
          - production
    name: Deploy ${{ needs.build.outputs.version }} to ${{ matrix.environment }}
    needs:
      - test
      - build
    environment:
      name: ${{ matrix.environment }}
      url: https://flex.${{ matrix.environment }}-sabio.cloud/CSS/SignIn.aspx
    steps:
      - name: deploy
        run: echo "deploy"
  rollback:
    continue-on-error: true
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - deploy
    steps:
      - uses: hmarr/debug-action@v2
  report:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs:
      - rollback
    steps:
      - uses: hmarr/debug-action@v2
