name: Deploy to Staging

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: version
        run: echo "::set-output name=version::0.0.1"
  test:
    runs-on: ubuntu-latest
    name: test
    needs:
      - build
    steps:
      - name: test
        run: echo "test"
  deploy:
    runs-on: ubuntu-latest
    name: Deploy ${{ needs.build.steps.version.output.version }} to Staging
    needs:
     - test
     - build
    environment: staging
    continue-on-error: true
    steps:
     - name: deploy
       run: echo "deploy"
  rollback:
   runs-on: ubuntu-latest
   needs:
     - deploy
   steps:
    - uses: hmarr/debug-action@v2
